name: 🤖 Patchwerk

on:
  # Workflow dispatch event to manually trigger the sync issues workflow
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  actions: write

# Any changes made to the workflow may be overwritten when the file is updated.
jobs:
  patchwerk-sync:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
    # Point the action to latest (@latest) or development (@main)
    uses: CBA-General/patchwerk/.github/workflows/patchwerk-sync-issues.yml@latest
    with:
      # The version of the tool to install, latest (@latest) or development (@main)
      version: "latest"
