name: Branch Checks
run-name: ${{ github.actor }} is running ${{ github.workflow }}

on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  id-token: write
  checks: write
  pull-requests: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  validate-pr-title:
    name: "Validate PR Title"
    uses: CBA-General/sre-gha-template/.github/workflows/reusable-validate-pr-title.yaml@main

  lint:
    name: Markdown Lint
    runs-on: default
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node 20.12.1
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.12.1
      - name: NPM Install
        run: npm ci

      - name: ESLint docusaurus source files
        run: |
          if npx eslint src; then
              echo "INFO: eslint passed for docusaurus source files"
          else
              echo "ERROR: eslint failed, please address the errors"
              exit 1
          fi

      - name: Lint Markdown
        run: |
          npx markdownlint --ignore _site/ --ignore node_modules/ --ignore docusaurus/node_modules/ --ignore docs/contributions/thanks.md "docs/**/*.md" --disable MD013 MD033 MD045 MD029 MD024 MD025 2> lint_output || true
          if [ -s lint_output ]; then
            cat lint_output
          fi

      - name: Validate Markdown Links
        run: |
          if npx remark . --use remark-validate-links --frail "docs/**/*.md"; then
              echo "INFO: Link check passed"
          else
              echo "ERROR: Link check failed"
              exit 1
          fi

      - name: Lint Summary
        id: lint_summary
        run: |
          summary_file="lint_summary.md"
          repo_url="https://github.com/${{ github.repository }}/blob/${{ github.sha }}"

          {
            echo "# Linting Summary"
            echo ""
            echo "## :warning: Warnings :warning:"
            echo ""
            echo "| File |  Message |"
            echo "| ---- |  ------- |"
          } >> lint_summary.md

          # There can be 10 annotations max per run
          while IFS= read -r line; do
           file=$(echo "$line" | cut -d: -f1)
            line_number=$(echo "$line" | cut -d: -f2)
            column=$(echo "$line" | cut -d: -f3 | cut -d' ' -f1)
            message=$(echo "$line" | cut -d' ' -f2-)
            echo "::warning file=$file,line=$line_number,col=$column::$message"

            file_link="[$file]($repo_url/$file?plain=1#L$line_number)"
            echo "| $file_link | $message |" >> $summary_file
          done < lint_output

          line_count=$(wc -l < lint_output | awk '{print $1}')
          echo "Total linting errors: $line_count"
          if [ "$line_count" -gt 0 ]; then
            echo "" >> $summary_file
            echo "Linting errors were found. Please review the warnings above." >> $summary_file
            cat $summary_file >> "$GITHUB_STEP_SUMMARY"
            echo "WARNINGS=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Delete previous comments
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            const botCommentIdentifier = '### :x: Linting Errors :x:';
            for (const comment of comments) {
              if (comment.user.login === 'github-actions[bot]' && comment.body.includes(botCommentIdentifier)) {
                await github.rest.issues.deleteComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: comment.id,
                });
              }
            }

      - name: Post PR comment
        if: steps.lint_summary.outputs.WARNINGS == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const branch = context.payload.pull_request.head.ref;
            const prNumber = context.issue.number;
            const runUrl = `https://github.com/${owner}/${repo}/actions/runs/${context.runId}`;

            const { data: commits } = await github.rest.pulls.listCommits({
              owner: owner,
              repo: repo,
              pull_number: prNumber,
            });
            const lastCommit = commits[commits.length - 1];
            const lastCommitter = lastCommit.author ? lastCommit.author.login : lastCommit.commit.author.name;

            const comment = `Markdown linting errors found, please correct them.\n\n[See here](${runUrl}) for more details\n`;
            github.rest.issues.createComment({
              issue_number: prNumber,
              owner: owner,
              repo: repo,
              body: `### :x: Linting Errors :x:\n${comment}\n\n@${lastCommitter}`
            });

      - name: Reflect results of lint in build status
        if: steps.lint_summary.outputs.WARNINGS == 'true'
        run: |
          echo "::error::Linting errors were found. Please review the warnings in the PR comment."
          exit 1

  check_build:
    name: Check build
    runs-on: default
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Node 20.20.0
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.20.0
      - name: NPM Install
        run: npm ci

      - name: NPM Build
        run: npm run generate-author-page && npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
